### ISSUE TITLE
Missing set number in legosets

### ISSUE THREAD

**Issue by spkaluzny** [jbryer/brickset#1]
One of the key information pieces for a Lego set is the set number. This is the number that Lego puts on the box next to the the set name. The `legosets` dataset and the results returned by `brickset::getSets` includes a column `setID` but not the number. The `setID` value appears to just be a unique id value for the item with no special relation to the item itself.

Your `sets_json` object that you create in `getSets` from the brickset.com download contains the set number in the `number` element. There is also a `numberVariant` element that goes with the `number` that uniquely identifies the item since sometimes the same number is used for multiple items.

I request that you include both the `number` and `numberVariant` columns in the results returned by `getSets` and in the helpful `legosets` dataset.

**Comment by jbryer** [comment]
Done in Github. Not sure when I'll update CRAN.
Do you know what the numberVariant values mean? Should it be recoded as a factor? I cannot find a description on the Brickset API website.

**Comment by spkaluzny** [comment]
On Thu, Mar 30, 2023 at 5:09 AM Jason Bryer ***@***.***>
wrote:

> Done in Github. Not sure when I'll update CRAN.
> Do you know what the numberVariant values mean? Should it be recoded as a
> factor? I cannot find a description on the Brickset API website.
>
Thanks for the quick update.

The numberVariant is an integer value that is added to the number to make a
unique number-numberVariant value to identify a Lego item. Most items have
a numberVariant of 1. The imageURL entry ends with number-NumberVariant.jpg
to uniquely identify the image.

The numberVariant should not be a factor.

-Stephen
